---
- name: Biuld and run docker file
  hosts: test-hosts
  gather_facts: False
  remote_user: deploy
  tasks:
     - name: copy new php files
       copy:
        src: /tmp/php-mysql-nginx/
        dest: /tmp/php-mysql-nginx/
     - name: run the service defined in container-php docker-compose.yml
       docker_service:
        project_src="/tmp/php-mysql-nginx/container-php/docker"
