---
- name: Biuld and run docker file
  hosts: test-hosts
  become: yes
  gather_facts: False
  remote_user: deploy
  tasks:
     - name: ping-to-ec2
       command: pip install docker-compose
     - name: run the service defined in container-php docker-compose.yml
       docker_service:
        project_src="{{ playbook_dir }}/container-php/docker"
